### ISSUE TITLE
Should hide/disable copy of file path in status bar

### ISSUE THREAD

**Issue by notnotdrew** [learn-co/learn-ide-tree#33]
We want to keep the local files somewhat hidden, and this exposes their location pretty easily. @aturkewi has encountered folks using this element as a way to get access to the local file, which is no bueno.

**Comment by aturkewi** [comment]
![screen shot 2017-01-18 at 4 54 01 pm](https://cloud.githubusercontent.com/assets/13033515/22084635/e20f2336-dd9e-11e6-85ae-c979b005ec15.png)
Screen shot just to point out exactly what I'm seeing here as well :)
